#ifndef ERRORDISPATCHER_H
#define ERRORDISPATCHER_H

#ifdef	__cplusplus
extern "C" {
#endif

    typedef enum {
	TRIPLET_ERROR_NONE,
	TRIPLET_ERROR_COM_EP, 
	TRIPLET_ERROR_COM_FJ,
	TRIPLET_ERROR_COM_DMD,
	TRIPLET_ERROR_FAN,
	TRIPLET_ERROR_LED_TEMP_MIN,
	TRIPLET_ERROR_LED_TEMP_MAX,
	TRIPLET_ERROR_LED_CURRENT,
	TRIPLET_ERROR_LED_VOLTAGE,
    } TRIPLET_ERROR_t;

  
#ifdef	__cplusplus
}
#endif

#endif // ERRORDISPATCHER_H
